In [1]:
import numpy as np

# Precision loss is closer to us than you think.
Create an array that starts at -0.6 and goes up to 0.2 in steps of 0.1 and store it in variable a4.

(The number 0.2 itself is not in the array)

In [5]:
a4 = np.arange(-0.6, 0.2, 0.1)

In [6]:
a4

array([-6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -1.11022302e-16,  1.00000000e-01])

# Diagonal 2-D array
Create an 4×4 array that its main diameter is equal to 1 and other elements are equal to zero 

and store this variable in a7 variable

In [12]:
a7 = np.eye(4, dtype=int)

In [13]:
a7

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Upper Diagonal Matrix
Create an 6×6 array that its second diameter above the main diameter is equal to 1 and other elements are equal to zero and store this variable in a8 variable

In [19]:
a8 = np.eye(6, k=2)

In [20]:
a8

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# Diagonal 2D Array
Create a 5×5 array that it's main diameter contains the numbers from 1 to 125 with equal distance and other elements are equal to zero then store it in the a9 variable.

In [22]:
a9 = np.diag(np.linspace(1, 125, 5))

In [23]:
a9

array([[  1.,   0.,   0.,   0.,   0.],
       [  0.,  32.,   0.,   0.,   0.],
       [  0.,   0.,  63.,   0.,   0.],
       [  0.,   0.,   0.,  94.,   0.],
       [  0.,   0.,   0.,   0., 125.]])