In [2]:
import numpy as np

# Precision loss is closer to us than you think.
Create an array that starts at -0.6 and goes up to 0.2 in steps of 0.1 and store it in variable a4.

(The number 0.2 itself is not in the array)

In [5]:
a4 = np.arange(-0.6, 0.2, 0.1)

In [6]:
a4

array([-6.00000000e-01, -5.00000000e-01, -4.00000000e-01, -3.00000000e-01,
       -2.00000000e-01, -1.00000000e-01, -1.11022302e-16,  1.00000000e-01])

# Diagonal 2-D array
Create an 4×4 array that its main diameter is equal to 1 and other elements are equal to zero 

and store this variable in a7 variable

In [12]:
a7 = np.eye(4, dtype=int)

In [13]:
a7

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

# Upper Diagonal Matrix
Create an 6×6 array that its second diameter above the main diameter is equal to 1 and other elements are equal to zero and store this variable in a8 variable

In [19]:
a8 = np.eye(6, k=2)

In [20]:
a8

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# Diagonal 2D Array
Create a 5×5 array that it's main diameter contains the numbers from 1 to 125 with equal distance and other elements are equal to zero then store it in the a9 variable.

In [22]:
a9 = np.diag(np.linspace(1, 125, 5))

In [23]:
a9

array([[  1.,   0.,   0.,   0.,   0.],
       [  0.,  32.,   0.,   0.,   0.],
       [  0.,   0.,  63.,   0.,   0.],
       [  0.,   0.,   0.,  94.,   0.],
       [  0.,   0.,   0.,   0., 125.]])

# Diagonal Array Indexing
A 5×5 array is stored in a variable named z, store the value of the second diameter lower than the main diameter in a variable called a10

In [8]:
z = np.arange(25).reshape(5, 5)

In [11]:
z

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [9]:
a10 = np.diag(z, -2)

In [10]:
a10

array([10, 16, 22])

# Random Array
Create a 6x4 array with all random elements and store it in variable a13 .

In [13]:
rng = np.random.default_rng(seed=None)

In [15]:
rng.random((6, 4))

array([[0.28663319, 0.28124465, 0.49241091, 0.754318  ],
       [0.43854998, 0.57989718, 0.26961229, 0.08495872],
       [0.92849765, 0.55764499, 0.42571313, 0.11369205],
       [0.30030378, 0.08130949, 0.70947495, 0.95837295],
       [0.61448963, 0.59356239, 0.28537565, 0.19909576],
       [0.01287736, 0.23425874, 0.78359459, 0.42139248]])

# An array with repeating rows
Using numpy with one line of code, create an array similar to the one below and store it in the a16  variable.
### array
      ([[-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf]])

In [19]:
a16 = np.full((6, 3), [-np.inf, np.nan, np.inf])

In [20]:
a16

array([[-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf]])