In [8]:
import numpy as np

# Empty and Full Numpy Array
#### Create a 3x4 empty numpy array
#### Create a 3x4 full numpy array where every element is equal to 55.

In [6]:
empty_array = np.empty((3, 4), dtype=int)
print(empty_array)

[[94623256455168              0   206158430253   193273528376]
 [  227633266738   210453397588   249108103218   223338299442]
 [  219043332154   197568495670   236223201332   386547056692]]


In [7]:
full_array = np.full((3, 4), 55, dtype=float)
print(full_array)

[[55. 55. 55. 55.]
 [55. 55. 55. 55.]
 [55. 55. 55. 55.]]


# Find Numpy Non-Zero Mean
Find the average of non-zero elements of a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 56]) .

In [30]:
a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 56])

In [31]:
a[a != 0].mean()

10.625

# Convert Python Sequences to 3D ndarray
Create a nested list in Python and store it in the python_list3 variable. Then create a three-dimensional ndarray using the python_list3 variable and store it in the ndarray_3d variable.

In [20]:
python_list3 = [[[1, 2, 3], [2, 3, 5], [3, 4, 6]], [[1, 2, 3], [2, 3, 5], [3, 4, 6]], [[1, 2, 3], [2, 3, 5], [3, 4, 6]]]

In [22]:
ndarray_3d = np.array(python_list3)
ndarray_3d

array([[[1, 2, 3],
        [2, 3, 5],
        [3, 4, 6]],

       [[1, 2, 3],
        [2, 3, 5],
        [3, 4, 6]],

       [[1, 2, 3],
        [2, 3, 5],
        [3, 4, 6]]])

# An array with 4-byte elements
Create a 2-dimensional array of size 3 x 4 named x, composed of 4-byte integer elements:

In [34]:
np.full((3, 4) , 6, dtype='i4')

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]], dtype=int32)